// Tag

export const PUSH_TAGS = 'PUSH_TAGS'
export const ADD_TAGS_STATE = 'ADD_TAGS_STATE'
export const GETTER_TAGS = 'GETTER_TAGS'
export const DELETE_TAG = 'DELETE_TAG'


//Staff 
export const PUSH_STAFFS = 'PUSH_STAFFS'
export const ADD_STAFFS_STATE = 'ADD_STAFFS_STATE'
export const GETTER_STAFFS = 'GETTER_STAFFS'
export const DELETE_STAFF = 'DELETE_STAFF'

//Career
export const PUSH_CAREERS = 'PUSH_CAREERS'
export const ADD_CAREERS_STATE = 'ADD_CAREERS_STATE'
export const GETTER_CAREERS = 'GETTER_CAREERS'
export const DELETE_CAREER = 'DELETE_CAREER'

//Project
export const PUSH_PROJECTS = 'PUSH_PROJECTS'
export const ADD_PROJECTS_STATE = 'ADD_PROJECTS_STATE'
export const GETTER_PROJECTS = 'GETTER_PROJECTS'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const PUSH_PROJECT = 'PUSH_PROJECT'
export const ADD_PROJECT_STATE = 'ADD_PROJECT_STATE'
export const GETTER_PROJECT = 'GETTER_PROJECT'
export const PUSH_PROJECTS_FILTER = 'PUSH_PROJECTS_FILTER'

export const CREATE_LINK = 'CREATE_LINK'
export const GETTER_LINK = 'GETTER_LINK'
export const DELETE_LINK = 'DELETE_LINK'
export const ADD_ALL_LINK = 'ADD_ALL_LINK'

export const PUSH_SECTION_TEXT = 'PUSH_SECTION_TEXT'
export const ADD_IMAGE_SECTION = 'ADD_IMAGE_SECTION'
export const PUSH_ALL_SECTION = 'PUSH_ALL_SECTION'
export const GETTER_SECTION = 'GETTER_SECTION'
export const DELETE_SECTION = 'DELETE_SECTION'
export const MOVE_SECTION = 'MOVE_SECTION'

export const CREATE_CREDIT = 'CREATE_CREDIT'
export const GETTER_CREDIT = 'GETTER_CREDIT'
export const DELETE_CREDIT = 'DELETE_CREDIT'
export const ADD_ALL_CREDIT = 'ADD_ALL_CREDIT'
export const TRIGGER_CREDIT_TYPE = 'TRIGGER_CREDIT_TYPE'

export const ADD_TEXT_CHECK = 'ADD_TEXT_CHECK'
export const GETTER_TEXT_CHECK = 'GETTER_TEXT_CHECK'

export const CLEAR_STATE_PROJECT = 'CLEAR_STATE_PROJECT'

export const ADD_MATCH_PROJECT = 'ADD_MATCH_PROJECT'
export const GETTER_MATCH_PROJECT = 'GETTER_MATCH_PROJECT'

export const TRIGGER_DROPDOWN = 'TRIGGER_DROPDOWN'
export const GETTER_DROPDOWN = 'GETTER_DROPDOWN'
export const FALSE_DROPDOWN = 'FALSE_DROPDOWN'

export const TRIGGER_LOADING = 'TRIGGER_LOADING'
export const GETTER_LOADING = 'GETTER_LOADING'